mars_rover:
    resource: "@MarsRoverBundle/Controller/DefaultController.php"
    prefix:     mars
    type:     annotation

flickr_flickr:
    resource: "@FlickrFlickrBundle/Resources/config/routing.yml"
    prefix:   /


app:
    resource: "@AppBundle/Controller/"
    type:     annotation
