flickr_flickr:
    resource: "@FlickrFlickrBundle/Resources/config/routing.yml"
    prefix:   /

first_first:
    resource: "@FirstFirstBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
