mars_rover:
    resource: "@MarsRoverBundle/Resources/config/routing.yml"
    prefix:     /

flickr_flickr:
    resource: "@FlickrFlickrBundle/Resources/config/routing.yml"
    prefix:   /


app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /
