homepage:
    path:     /{_locale}
    defaults: { _controller: AppBundle:Default:index }
    requirements:
            _locale: gb|us|ru|en|en_GB|en_US|fr|ru_RU


_ajax:
    path:     /ajax
    defaults: { _controller: AppBundle:Default:ajax }
    requirements: