homepage:
    path:     /{_locale}
    defaults: { _controller: AppBundle:Default:index }
    requirements:
            _locale: en|en_GB|en_US|fr|ru


_ajax:
    path:     /ajax
    defaults: { _controller: AppBundle:Default:ajax }
    requirements: