#mars_rover_homepage:
#    path:     /mars
#    defaults: { _controller: MarsRoverBundle:Default:index }

mars_rover:
    path:     /{_locale}/mars
    defaults: { _controller: MarsRoverBundle:Default:index }
    requirements:
            _locale: gb|us|ru|en|en_GB|en_US|fr|ru_RU

